name: Build, Test & Lint

on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: |
          if [ "${{ inputs.run-tests }}" = "true" ]; then
            mvn -B clean install
          else
            mvn -B clean install -DskipTests
          fi

      - name: Upload test results
        if: ${{ inputs.run-tests }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/target/surefire-reports/*.xml'

  lint:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Spotless (format check)
        run: mvn spotless:check

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run SpotBugs
        run: mvn spotbugs:check